#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "\033[0;31mYou can't commit directly to the master branch. Create a PR!"
  exit 1
fi

yarn prettier:write
git add .